---
title: "Gov 50 Final Project"
author: "Sungjoo Yoon"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Does the socioeconomic status of a Los Angeles neighborhood influence rates of sexual violence? In this study, I plan to examine the extent to which affluence alters the frequency of crimes such as rape or intimate assault. I hypothesize that said crimes are likely to occur at a higher rate within lower-income communities, relative to higher-income communities; and that values will fall along in a scalar manner. Within lower-income neighborhoods, potential victims are seen as more vulnerable given their lack of restorative resources, and potential perpetrators may have higher rates of self-injurious, non-sexual stressors (such as drug usage, hostility towards the world, etc). My sample consists of raw crime data from the City of Los Angeles from 2020 to 2023. My unit of analysis is the frequency of a reported crime of sexual violence, and the explanatory variable of interest is a defined neighborhood inside of the city — particularly in relation to its socioeconomic standing. The variable is coded by the name of the neighborhood (e.g. “N Hollywood”), while the outcome variable is the count of a reported crime of sexual violence divided by the number of individuals in a given neighborhood. For instance, if there were “x” amount of crimes of sexual violence divided by “y” amount of people in “z” neighborhood, the value “x/y” would be the area-specific frequency that we are attempting to analyze. If I were to observe greater rates of crimes of sexual violence under lower-income areas, this would provide support for my hypothesis (in essence, regression of these rates with said reas ought to provide a positive correlation). Contrarily, if I were to observe similar or lower rates of crimes of sexual violence, this would provide evidence against my original theory. 

```{r}
library(readr)
library(readr)
lacrimedata <- read_csv("lacrimedata.csv")
```

